FROM anapsix/docker-oracle-java8

VOLUME /tmp
ADD magic8ball-service.jar /opt/magic8ball-service/
EXPOSE 8080
WORKDIR /opt/magic8ball-service/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "magic8ball-service.jar"]
